### ISSUE TITLE
FirebaseDynamicLinks code crashes Android app

### ISSUE THREAD

**Issue by bizz84** [bizz84/passwordless_sign_in_firebase_flutter#4] opened 2019-02-05 11:46 UTC
This document shows how to handle incoming dynamic links on Android:

https://firebase.google.com/docs/dynamic-links/android/receive

However, after implementing this, the app crashes on startup.

Any idea why? I don't get any console logs so I'm not sure what is the problem.

**Comment by bizz84** [comment] 2019-02-05 11:46
@paolorotolo is this something that you're familiar with?

**Comment by paolorotolo** [comment] 2019-02-05 13:34
Yes, I will have a look at it as soon as possible.

**Comment by paolorotolo** [comment] 2019-02-05 20:19
Can't reproduce the crash on startup on Android Pie. Do you have more details to share?

**Comment by bizz84** [comment] 2019-02-05 20:38
It seems like this is the error I get:
```
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:8100/ws
```
This issue has been reported here:

https://github.com/flutter/flutter/issues/19056

From what I can see in [this comment](https://github.com/flutter/flutter/issues/19056#issuecomment-402418527), it may be a problem with the Android emulator. The one I'm using is a Nexus 5X API 28 with Android 9.0.

@paolorotolo Does it work for you on the device?
Also I'm not sure if I definitely need `FirebaseDynamicLinks` in my `MainActivity` (I have been able to get this working on iOS without it).

Does the Firebase documentation make sense to you / have you been able to get the email link to open the app? I didn't.

**Comment by paolorotolo** [comment] 2019-02-05 20:41
The app works on my device with Pie, so yeah it may be an emulator issue.
Anyway, I never get redirected to login page, the "Send email link" button does nothing.
Can we set up a faster method to chat about the project (maybe come to Twitter DM)?

**Comment by paolorotolo** [comment] 2019-02-05 21:08
Confirmed this is emulator related. We can close this.

**Closed as completed** 2019-02-05 21:42 UTC
